/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../lib/db`; params?: Router.UnknownInputParams; } | { pathname: `/../types/entry`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/timeUtils`; params?: Router.UnknownInputParams; } | { pathname: `/add-entry`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-entry` | `/add-entry`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../lib/db`; params?: Router.UnknownOutputParams; } | { pathname: `/../types/entry`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/timeUtils`; params?: Router.UnknownOutputParams; } | { pathname: `/add-entry`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/add-entry` | `/add-entry`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../lib/db${`?${string}` | `#${string}` | ''}` | `/../types/entry${`?${string}` | `#${string}` | ''}` | `/../lib/timeUtils${`?${string}` | `#${string}` | ''}` | `/add-entry${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/add-entry${`?${string}` | `#${string}` | ''}` | `/add-entry${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../lib/db`; params?: Router.UnknownInputParams; } | { pathname: `/../types/entry`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/timeUtils`; params?: Router.UnknownInputParams; } | { pathname: `/add-entry`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-entry` | `/add-entry`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
